In [ ]:


# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

In [3]:
#Step 2: Importing the dataset
dataset = pd.read_csv('https://raw.githubusercontent.com/mk-gurucharan/Classification/master/IrisDataset.csv')

In [5]:
#Step 3:Describe dataset,See dimention and Exlpore dataset
dataset.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [7]:
X = dataset.iloc[:,:4].values
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [9]:
y = dataset['species'].values
y


array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [11]:
#Step 4: Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [13]:
#Step 5: Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_train

array([[-0.94838282,  1.65702229, -1.32624353, -1.21436561],
       [ 0.50445895, -0.3447496 ,  1.0276952 ,  0.76021262],
       [-0.22196194, -1.234426  ,  0.68321636,  1.02348972],
       [-1.4326634 ,  0.32250769, -1.26883039, -1.34600416],
       [-0.10089179, -0.5671687 ,  0.7406295 ,  1.55004391],
       [-1.31159326,  0.76734589, -1.26883039, -1.34600416],
       [-0.94838282,  0.76734589, -1.32624353, -1.34600416],
       [-1.06945296, -1.6792642 , -0.29280701, -0.29289577],
       [-1.19052311,  0.10008859, -1.32624353, -1.47764271],
       [ 2.199441  ,  1.65702229,  1.65923974,  1.28676681],
       [-0.10089179, -0.7895878 ,  0.16649811, -0.29289577],
       [-1.06945296,  0.32250769, -1.49848295, -1.34600416],
       [ 0.3833888 ,  0.76734589,  0.91286892,  1.41840536],
       [-0.22196194,  2.99153689, -1.32624353, -1.08272706],
       [-0.82731267,  2.32427959, -1.32624353, -1.47764271],
       [-0.10089179, -1.0120069 ,  0.10908497, -0.02961867],
       [ 2.199441  , -0.

In [15]:
X_test

array([[-0.22196194, -1.0120069 , -0.17798073, -0.29289577],
       [-0.10089179, -0.7895878 ,  0.7406295 ,  0.89185117],
       [-0.58517238, -0.1223305 ,  0.39615066,  0.36529697],
       [ 0.50445895,  0.54492679,  1.25734776,  1.68168246],
       [-0.82731267, -0.7895878 ,  0.05167183,  0.23365842],
       [ 1.83623056, -0.5671687 ,  1.3147609 ,  0.89185117],
       [-1.06945296,  0.76734589, -1.26883039, -1.08272706],
       [ 0.86766939, -0.3447496 ,  0.4535638 ,  0.10201988],
       [ 0.3833888 , -1.9016833 ,  0.39615066,  0.36529697],
       [ 0.3833888 , -0.5671687 ,  0.56839008,  0.76021262],
       [-0.58517238,  1.43460319, -1.32624353, -1.34600416],
       [ 1.71516041, -0.3447496 ,  1.42958718,  0.76021262],
       [ 0.1412485 , -0.1223305 ,  0.56839008,  0.76021262],
       [ 0.26231865, -0.5671687 ,  0.51097694, -0.02961867],
       [ 0.3833888 , -0.3447496 ,  0.28132439,  0.10201988],
       [-1.31159326, -0.1223305 , -1.38365667, -1.47764271],
       [-1.31159326, -0.

In [17]:
#Step 6: Training the Naive Bayes Classification model on the Training Set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [19]:
y_pred = classifier.predict(X_test) 
y_pred


array(['versicolor', 'virginica', 'versicolor', 'virginica', 'versicolor',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'virginica', 'virginica', 'versicolor', 'versicolor',
       'setosa', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'virginica', 'versicolor',
       'setosa', 'virginica', 'virginica'], dtype='<U10')

In [21]:
y_pred[0]

'versicolor'

In [23]:
y_test[0]

'versicolor'

In [25]:
#Step 7: Confusion Matrix and Accuracy
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[12,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 10]], dtype=int64)

In [29]:
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Calculate metrics
accuracy = accuracy_score(y_test, y_pred)
error_rate = 1 - accuracy
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')

# Print metrics
print("Confusion Matrix:\n", cm)
print(f"Accuracy: {accuracy:.2f}")
print(f"Error Rate: {error_rate:.2f}")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")

Confusion Matrix:
 [[12  0  0]
 [ 0  8  0]
 [ 0  0 10]]
Accuracy: 1.00
Error Rate: 0.00
Precision: 1.00
Recall: 1.00
